// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniApm.Infrastructure.Persistence;

#nullable disable

namespace MiniApm.Infrastructure.Migrations
{
    [DbContext(typeof(MiniApmDbContext))]
    [Migration("20260423170842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniApm.Domain.Entities.SystemMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AvailableMemory")
                        .HasColumnType("float");

                    b.Property<int>("CpuCoreCount")
                        .HasColumnType("int");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("float");

                    b.Property<double>("DiskUsage")
                        .HasColumnType("float");

                    b.Property<double>("FreeDisk")
                        .HasColumnType("float");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("float");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalDisk")
                        .HasColumnType("float");

                    b.Property<double>("TotalMemory")
                        .HasColumnType("float");

                    b.Property<double>("UsedDisk")
                        .HasColumnType("float");

                    b.Property<double>("UsedMemory")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SystemMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
